name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Security and Code Quality
  security:
    name: Security & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Display Trivy scan summary
        if: always()
        run: |
          echo "=== Trivy Scan Summary ==="
          if [ -f "trivy-results.sarif" ]; then
            echo "✅ Trivy scan completed successfully"
            echo "📄 Results saved to: trivy-results.sarif"
          else
            echo "⚠️  Trivy scan completed but no results file found"
          fi

      - name: Check if Trivy results exist
        if: always()
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "Trivy results file exists"
            ls -la trivy-results.sarif
            echo "File content preview:"
            head -20 trivy-results.sarif
          else
            echo "Trivy results file not found"
          fi

      # Comment out SARIF upload for now - can be re-enabled later
      # - name: Upload Trivy scan results
      #   uses: github/codeql-action/upload-sarif@v3
      #   if: always()
      #   with:
      #     sarif_file: 'trivy-results.sarif'

      - name: Run Bandit security linter
        run: |
          pip install bandit
          bandit -r backend/ -f json -o bandit-report.json || echo "Bandit scan completed with warnings"
          if [ -f "bandit-report.json" ]; then
            echo "Bandit report generated"
          else
            echo "No Bandit report generated"
          fi

  # Backend Testing
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linting
        working-directory: ./backend
        run: |
          make lint

      - name: Run unit tests
        working-directory: ./backend
        run: |
          make test

      - name: Run security tests
        working-directory: ./backend
        run: |
          make test-security

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.12'
        with:
          file: ./backend/.coverage
          flags: backend
          name: backend-coverage

  # Frontend Testing
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run linting
        working-directory: ./frontend
        run: npm run lint

      - name: Build application
        working-directory: ./frontend
        run: npm run build

  # Docker Build and Test
  docker-build:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Dockerfiles
        run: |
          echo "=== Checking Dockerfiles ==="
          if [ -f "backend/Dockerfile" ]; then
            echo "✅ Backend Dockerfile exists"
            ls -la backend/Dockerfile
          else
            echo "❌ Backend Dockerfile not found"
            exit 1
          fi
          
          if [ -f "frontend/Dockerfile" ]; then
            echo "✅ Frontend Dockerfile exists"
            ls -la frontend/Dockerfile
          else
            echo "❌ Frontend Dockerfile not found"
            exit 1
          fi
          
          if [ -f "docker-compose.yml" ]; then
            echo "✅ Docker Compose file exists"
            ls -la docker-compose.yml
          else
            echo "❌ Docker Compose file not found"
            exit 1
          fi

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # Note: Requires repository permissions for "Contents" and "Packages"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Backend image
        id: backend-push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1
        continue-on-error: true

      - name: Build and push Frontend image
        id: frontend-push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}-frontend
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1
        continue-on-error: true

      - name: Check push status and provide guidance
        if: always()
        run: |
          echo "=== Push Status Check ==="
          if [ "${{ steps.backend-push.outputs.status }}" == "success" ]; then
            echo "✅ Backend image pushed successfully"
          else
            echo "⚠️  Backend image push failed - likely due to GHCR permissions"
            echo "📋 To fix this, ensure:"
            echo "   1. Repository has 'Packages' permission enabled"
            echo "   2. GitHub Actions has write access to packages"
            echo "   3. Organization allows package creation"
          fi
          
          if [ "${{ steps.frontend-push.outputs.status }}" == "success" ]; then
            echo "✅ Frontend image pushed successfully"
          else
            echo "⚠️  Frontend image push failed - likely due to GHCR permissions"
          fi

      - name: Build local images for testing
        run: |
          echo "=== Building Local Images for Testing ==="
          echo "Building backend image locally..."
          docker build -t backend-test ./backend
          echo "Building frontend image locally..."
          docker build -t frontend-test ./frontend
          echo "✅ Local images built successfully"

      - name: Test Docker containers
        run: |
          echo "=== Testing Docker Containers ==="
          echo "Starting containers..."
          docker compose up -d
          echo "Waiting for services to start..."
          sleep 30
          
          echo "Checking container status..."
          docker compose ps
          
          echo "Testing backend health..."
          if curl -f http://localhost:8000/api/v1/health; then
            echo "✅ Backend health check passed"
          else
            echo "❌ Backend health check failed"
            echo "Backend logs:"
            docker compose logs backend
            exit 1
          fi
          
          echo "Testing frontend..."
          if curl -f http://localhost:80/; then
            echo "✅ Frontend check passed"
          else
            echo "❌ Frontend check failed"
            echo "Frontend logs:"
            docker compose logs frontend
            exit 1
          fi
          
          echo "Stopping containers..."
          docker compose down
          echo "=== Docker test completed ==="

  # Integration Tests
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run integration tests
        working-directory: ./backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          make test-integration

  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [integration-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Add your staging deployment logic here
          # Example: kubectl apply, docker compose, etc.

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [integration-test]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add your production deployment logic here
          # Example: kubectl apply, docker compose, etc.
